import type { Metadata } from "next";
import "../../shared/ui/styles/globals.css";


export const metadata: Metadata = {
  title: "EdYOf Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient-to-br from-blue-50 to-indigo-100`}
      >
        {children}
      </body>
    </html>
  );
}
