import { MigrationInterface, QueryRunner } from "typeorm";

export class Schema1783063705557 implements MigrationInterface {
    name = 'Schema1783063705557'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "employee_role" ("employee_role_id" BIGSERIAL NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_52eb6141f7e93dae55ce01955bb" UNIQUE ("name"), CONSTRAINT "PK_790b9cdd2ac1c0eb09df2500493" PRIMARY KEY ("employee_role_id"))`);
        await queryRunner.query(`CREATE TABLE "customer" ("customer_id" BIGSERIAL NOT NULL, "establishment_id" bigint, "first_name" character varying(150) NOT NULL, "sale_default" boolean NOT NULL, "last_name" character varying(100), "company_name" character varying(150), "phone_number" character varying(25), "rfc" character varying(13), "email" character varying(100), "customer_type" character varying(50), "address_id" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fdb2f3ad8115da4c7718109a6eb" UNIQUE ("email"), CONSTRAINT "UQ_23810fb397050d8ac37dae44ff6" UNIQUE ("address_id"), CONSTRAINT "REL_23810fb397050d8ac37dae44ff" UNIQUE ("address_id"), CONSTRAINT "PK_cde3d123fc6077bcd75eb051226" PRIMARY KEY ("customer_id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("category_id" BIGSERIAL NOT NULL, "establishment_id" bigint NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cc7f32b7ab33c70b9e715afae84" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TABLE "brand" ("brand_id" BIGSERIAL NOT NULL, "establishment_id" bigint NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a6201ff889d4681c6e521d26231" PRIMARY KEY ("brand_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_item_location_enum" AS ENUM('venta', 'almacen', 'dañado', 'viajando')`);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("inventory_item_id" BIGSERIAL NOT NULL, "inventory_id" bigint NOT NULL, "location" "public"."inventory_item_location_enum", "quantity_on_hand" numeric(18,3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2bbb156c5e22a172468f04b0ec8" PRIMARY KEY ("inventory_item_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_from_location_enum" AS ENUM('venta', 'almacen', 'dañado', 'viajando')`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_to_location_enum" AS ENUM('venta', 'almacen', 'dañado', 'viajando')`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_status_enum" AS ENUM('Pendiente', 'Aprobada', 'En Transito', 'Recibida', 'Cancelada')`);
        await queryRunner.query(`CREATE TABLE "transfer" ("transfer_id" BIGSERIAL NOT NULL, "inventory_id" bigint, "from_branch_office_id" bigint, "from_location" "public"."transfer_from_location_enum", "to_branch_office_id" bigint NOT NULL, "to_location" "public"."transfer_to_location_enum" NOT NULL, "quantity_required" numeric(18,3) NOT NULL, "quantity_transferred" numeric(18,3), "requested_by_employee_id" bigint NOT NULL, "approved_by_employee_id" bigint, "shipped_by_employee_id" bigint, "received_by_employee_id" bigint, "transfer_request_date" TIMESTAMP WITH TIME ZONE NOT NULL, "transfer_shipped_date" TIMESTAMP WITH TIME ZONE, "transfer_received_date" TIMESTAMP WITH TIME ZONE, "status" "public"."transfer_status_enum" NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7aa3769048ff14716eb5e0939e1" PRIMARY KEY ("transfer_id"))`);
        await queryRunner.query(`CREATE TABLE "returns" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "returns_id" BIGSERIAL NOT NULL, "sale_detail_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "inventory_id" bigint NOT NULL, "quantity_return" numeric(18,3) NOT NULL, "amount_return" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "PK_23e57be85bfdba70dff9319d969" PRIMARY KEY ("returns_id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("inventory_id" BIGSERIAL NOT NULL, "product_id" bigint NOT NULL, "branch_office_id" bigint NOT NULL, "internalBarCode" character varying(100), "sale_price_one" numeric(12,2), "sale_price_many" numeric(12,2), "sale_quantity_many" numeric(18,4), "sale_price_special" numeric(12,2), "min_stock_branch" numeric(18,3), "max_stock_branch" numeric(18,3), "is_sellable" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_732fdb1f76432d65d2c136340d" UNIQUE ("product_id"), CONSTRAINT "PK_711db979ad954f0ab33e3eea53a" PRIMARY KEY ("inventory_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lot_unit_purchase_unit_enum" AS ENUM('kg', 'l', 'm', 'pc', 'doc', 'paquete', 'caja', 'set')`);
        await queryRunner.query(`CREATE TABLE "lot_unit_purchase" ("lot_unit_purchase_id" BIGSERIAL NOT NULL, "lot_id" bigint NOT NULL, "purchase_price" numeric(18,2) NOT NULL, "purchase_quantity" numeric(18,3) NOT NULL, "unit" "public"."lot_unit_purchase_unit_enum" NOT NULL, "units_in_purchase_unit" numeric(18,3) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_dadbb838015e6b41c2683c052ad" PRIMARY KEY ("lot_unit_purchase_id"))`);
        await queryRunner.query(`CREATE TABLE "suplier" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "suplier_id" BIGSERIAL NOT NULL, "establishment_id" bigint NOT NULL, "address_id" bigint, "name" character varying(150) NOT NULL, "phone_number" character varying(25), "rfc" character varying(13), "contact_person" character varying(100), "email" character varying(100), "notes" text, CONSTRAINT "UQ_d9aa066a07cc860ebf5368c5bb3" UNIQUE ("rfc"), CONSTRAINT "UQ_2c4044f9dfcf5e2401af2b1fe18" UNIQUE ("email"), CONSTRAINT "REL_99627221092cc52719692a21ff" UNIQUE ("address_id"), CONSTRAINT "PK_b220fa0770e30166f3b2fb73445" PRIMARY KEY ("suplier_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lot_purchase_unit_enum" AS ENUM('kg', 'l', 'm', 'pc', 'doc', 'paquete', 'caja', 'set')`);
        await queryRunner.query(`CREATE TABLE "lot" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "lot_id" BIGSERIAL NOT NULL, "product_id" bigint NOT NULL, "suplier_id" bigint, "lot_number" character varying(50) NOT NULL, "purchase_price" numeric(12,4) NOT NULL, "purchase_unit" "public"."lot_purchase_unit_enum" NOT NULL, "initial_quantity" numeric(18,3) NOT NULL, "expiration_date" date, "manufacturing_date" date, "received_date" date NOT NULL DEFAULT ('now'::text)::date, CONSTRAINT "PK_0b12153cdb29b8016846629c89f" PRIMARY KEY ("lot_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_47dc7829fdca47653512ca28e2" ON "lot" ("product_id", "lot_number") `);
        await queryRunner.query(`CREATE TABLE "season" ("season_id" BIGSERIAL NOT NULL, "establishment_id" bigint NOT NULL, "name" character varying(100) NOT NULL, "description" text, "date_init" date, "date_finish" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3b43f8b4429c26d79b572a3cc19" PRIMARY KEY ("season_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_unit_of_measure_enum" AS ENUM('kg', 'l', 'm', 'pc', 'doc', 'paquete', 'caja', 'set')`);
        await queryRunner.query(`CREATE TABLE "product" ("product_id" BIGSERIAL NOT NULL, "establishment_id" bigint NOT NULL, "category_id" bigint NOT NULL, "brand_id" bigint, "season_id" bigint, "name" character varying(150) NOT NULL, "sku" character varying(50), "universal_bar_code" character varying(100), "description" text, "unit_of_measure" "public"."product_unit_of_measure_enum" NOT NULL, "min_stock_global" numeric(18,3) NOT NULL DEFAULT '0', "image_url" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1de6a4421ff0c410d75af27aeee" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8257684c84ab2a533ec9f76be3" ON "product" ("establishment_id", "universal_bar_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b7fc615c93ad77e766374b5e1d" ON "product" ("establishment_id", "sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_57aaf9f1e2f450783692c0d977" ON "product" ("establishment_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."sale_detail_salefor_enum" AS ENUM('Menudeo', 'Mayoreo', 'Especial')`);
        await queryRunner.query(`CREATE TABLE "sale_detail" ("sale_detail_id" BIGSERIAL NOT NULL, "sale_id" bigint NOT NULL, "product_id" bigint NOT NULL, "inventory_id" bigint NOT NULL, "product_name_at_sale" character varying(100) NOT NULL, "product_description_at_sale" text, "product_bar_code_at_sale" character varying(100) NOT NULL, "product_brand_at_sale" character varying(100), "product_category_at_sale" character varying(100), "product_unit_at_sale" character varying(20) NOT NULL, "quantity" numeric(18,3) NOT NULL, "unit_price_at_sale" numeric(12,2) NOT NULL, "regular_price_at_sale" numeric(12,2) NOT NULL, "discount_item" numeric(12,2) NOT NULL DEFAULT '0', "saleFor" "public"."sale_detail_salefor_enum" NOT NULL, "subtotal_item" numeric(14,2) NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4367e56d9cbc98497e1b37d3b1b" PRIMARY KEY ("sale_detail_id"))`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("payment_method_id" BIGSERIAL NOT NULL, "name" character varying(50) NOT NULL, "requires_reference" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_6101666760258a840e115e1bb11" UNIQUE ("name"), CONSTRAINT "PK_ed16884cd19aa06b5eafbf0e013" PRIMARY KEY ("payment_method_id"))`);
        await queryRunner.query(`CREATE TABLE "sale_payment" ("sale_payment_id" BIGSERIAL NOT NULL, "sale_id" bigint NOT NULL, "payment_method_id" bigint NOT NULL, "amount_paid" numeric(18,2) NOT NULL, "reference_number" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a586227d6b30952b0db95c502fd" PRIMARY KEY ("sale_payment_id"))`);
        await queryRunner.query(`CREATE TABLE "cash_register" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "cash_register_id" BIGSERIAL NOT NULL, "branch_office_id" bigint NOT NULL, "name" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d2e649aaa6bbcaa26ba2334a154" PRIMARY KEY ("cash_register_id"))`);
        await queryRunner.query(`CREATE TABLE "cash_session" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "cash_session_id" BIGSERIAL NOT NULL, "cash_register_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "start_balance" numeric(14,2) NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE, "expected_balance" numeric(14,2), "actual_balance" numeric(14,2), "difference" numeric(14,2), "is_closed" boolean NOT NULL DEFAULT false, "closing_notes" text, CONSTRAINT "PK_59aa5e4aacd1e4cc97c8d5ff54d" PRIMARY KEY ("cash_session_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_account_type_enum" AS ENUM('Ingreso', 'Egreso')`);
        await queryRunner.query(`CREATE TABLE "transaction_type" ("transaction_type_id" BIGSERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "account_type" "public"."transaction_type_account_type_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_8705cb9b813ab0ae38cdf39c8ee" UNIQUE ("name"), CONSTRAINT "PK_fa15cdd9f6ea232ff4f50c0970c" PRIMARY KEY ("transaction_type_id"))`);
        await queryRunner.query(`CREATE TABLE "transaction" ("trsansaction_id" BIGSERIAL NOT NULL, "transaction_type_id" bigint NOT NULL, "branch_office_id" bigint NOT NULL, "purchase_id" bigint, "sale_id" bigint, "cash_session_id" bigint, "employee_id" bigint NOT NULL, "amount" numeric(14,2) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cbde49e98837ac0602abd2961af" PRIMARY KEY ("trsansaction_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_status_enum" AS ENUM('inicializada', 'pendiente', 'completada', 'cancelada', 'reembolsada')`);
        await queryRunner.query(`CREATE TABLE "sale" ("sale_id" BIGSERIAL NOT NULL, "branch_office_id" bigint NOT NULL, "customer_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "cash_session_id" bigint NOT NULL, "sub_total_amount" numeric(14,2) NOT NULL DEFAULT '0', "discount_amount" numeric(14,2) NOT NULL DEFAULT '0', "tax_amount" numeric(14,2) NOT NULL DEFAULT '0', "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "in_amount" numeric(14,2) NOT NULL DEFAULT '0', "out_amount" numeric(14,2) NOT NULL DEFAULT '0', "status" "public"."sale_status_enum" NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1f5c38463e847a2a0e74cf8035a" PRIMARY KEY ("sale_id"))`);
        await queryRunner.query(`CREATE TABLE "permission" ("permission_id" BIGSERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_240853a0c3353c25fb12434ad33" UNIQUE ("name"), CONSTRAINT "PK_aaa6d61e22fb453965ae6157ce5" PRIMARY KEY ("permission_id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_permission_id" BIGSERIAL NOT NULL, "permission_id" bigint NOT NULL, "role_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c1ef7e8a7f2bcf5393d185505db" PRIMARY KEY ("role_permission_id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("role_id" BIGSERIAL NOT NULL, "name" character varying(50) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_df46160e6aa79943b83c81e496e" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TABLE "user_role" ("user_role_id" BIGSERIAL NOT NULL, "user_id" bigint NOT NULL, "role_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_77580f3bab637e39a7fdd01a94c" PRIMARY KEY ("user_role_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("user_id" BIGSERIAL NOT NULL, "employee_id" bigint NOT NULL, "username" character varying(100) NOT NULL, "email" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_135936b6918bd375a4479b9231" UNIQUE ("employee_id"), CONSTRAINT "PK_758b8ce7c18b9d347461b30228d" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_gender_enum" AS ENUM('masculino', 'femenino', 'otro')`);
        await queryRunner.query(`CREATE TABLE "employee" ("employee_id" BIGSERIAL NOT NULL, "branch_office_id" bigint NOT NULL, "employee_role_id" bigint NOT NULL, "address_id" bigint, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "email" character varying(100), "phone_number" character varying(25), "birth_date" TIMESTAMP WITH TIME ZONE, "gender" "public"."employee_gender_enum", "hire_date" TIMESTAMP WITH TIME ZONE, "termination_date" TIMESTAMP WITH TIME ZONE, "entry_time" TIME, "exit_time" TIME, "current_salary" numeric(10,2) DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "photo_url" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_2a4f5082f1be346e2b8cdec219" UNIQUE ("address_id"), CONSTRAINT "PK_f9d306b968b54923539b3936b03" PRIMARY KEY ("employee_id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "address_id" BIGSERIAL NOT NULL, "street" character varying(255), "external_number" character varying(20), "internal_number" character varying(20), "municipality" character varying(100) NOT NULL, "neighborhood" character varying(100), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postal_code" character varying(10) NOT NULL, "country" character varying(100) NOT NULL, "reference" text, CONSTRAINT "PK_db4aae0a059fd4ef7709cb802b0" PRIMARY KEY ("address_id"))`);
        await queryRunner.query(`CREATE TABLE "branch_office" ("branch_office_id" BIGSERIAL NOT NULL, "cloud_branch_office_id" bigint, "address_id" bigint NOT NULL, "establishment_id" bigint NOT NULL, "name" character varying(250) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b60100709d7f1bba4028c87bf99" UNIQUE ("address_id"), CONSTRAINT "REL_b60100709d7f1bba4028c87bf9" UNIQUE ("address_id"), CONSTRAINT "PK_7471928922911b9a2539c74a98e" PRIMARY KEY ("branch_office_id"))`);
        await queryRunner.query(`CREATE TABLE "establishment" ("establishment_id" BIGSERIAL NOT NULL, "cloud_establishment_id" bigint, "enrollment_key" character varying(255), "name" character varying(250) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_0de875a393b6ec2c01b1770ae1e" UNIQUE ("enrollment_key"), CONSTRAINT "UQ_58a3c0e6b35c7e30aa3a58b3afd" UNIQUE ("name"), CONSTRAINT "PK_48297b8d13bd60cbad537ed3545" PRIMARY KEY ("establishment_id"))`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_23810fb397050d8ac37dae44ff6" FOREIGN KEY ("address_id") REFERENCES "address"("address_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_c48f6f5c750b8e0de0c4b41bde7" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_2e1a2e8a187a8ee29bfe143034a" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brand" ADD CONSTRAINT "FK_0574a2ace361e0a309629993228" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_a2129b235bd560a0a725ae3404b" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("inventory_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_e2bad4f0b033667a33ea21159d9" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("inventory_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_d4aa6f098fca4e9f3e5cc20efaa" FOREIGN KEY ("from_branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_a328ca7219e70e3222adaaf43e3" FOREIGN KEY ("to_branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_bd077bffe7cc45942115d1e1a6f" FOREIGN KEY ("requested_by_employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_967eed20693cb0a99a63501d329" FOREIGN KEY ("approved_by_employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_1ae9614b29392c195f75ff63265" FOREIGN KEY ("shipped_by_employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_612f938aeee343d52fb045e3b60" FOREIGN KEY ("received_by_employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "returns" ADD CONSTRAINT "FK_c79e321a198b9a794c9b4197290" FOREIGN KEY ("sale_detail_id") REFERENCES "sale_detail"("sale_detail_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "returns" ADD CONSTRAINT "FK_b3994d9ce84eb746e266929eb43" FOREIGN KEY ("employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "returns" ADD CONSTRAINT "FK_5f8ec9dd564e7ae386c8bfb3421" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("inventory_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_732fdb1f76432d65d2c136340dc" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_735e19a378152b4fadfb7c82852" FOREIGN KEY ("branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lot_unit_purchase" ADD CONSTRAINT "FK_7e93cb81b9500f42b10cdf3f6dc" FOREIGN KEY ("lot_id") REFERENCES "lot"("lot_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suplier" ADD CONSTRAINT "FK_60bc300997b579e59bc75ad3601" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suplier" ADD CONSTRAINT "FK_99627221092cc52719692a21ff6" FOREIGN KEY ("address_id") REFERENCES "address"("address_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lot" ADD CONSTRAINT "FK_e79764f0f61ae488d54f3170923" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lot" ADD CONSTRAINT "FK_89eb6f642cad1024527b0f13e54" FOREIGN KEY ("suplier_id") REFERENCES "suplier"("suplier_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "season" ADD CONSTRAINT "FK_6fe6e856caf37532769499a2baf" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_9442f51326c1f2588083345d8fb" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_2eb5ce4324613b4b457c364f4a2" FOREIGN KEY ("brand_id") REFERENCES "brand"("brand_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_aa365031a50f63a92601192e5f5" FOREIGN KEY ("season_id") REFERENCES "season"("season_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a" FOREIGN KEY ("sale_id") REFERENCES "sale"("sale_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_6f193a6e12bed09dc343ad057ab" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_8f79a9318b851af5c24cabfd510" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("inventory_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payment" ADD CONSTRAINT "FK_e6064f0e7a5404cca890a994c35" FOREIGN KEY ("sale_id") REFERENCES "sale"("sale_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payment" ADD CONSTRAINT "FK_ed5e4187840fb479d16c60935e0" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("payment_method_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_register" ADD CONSTRAINT "FK_516c78eb890a8647e13328e328f" FOREIGN KEY ("branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_session" ADD CONSTRAINT "FK_f823f4771aa4181f79c13bc6283" FOREIGN KEY ("cash_register_id") REFERENCES "cash_register"("cash_register_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_session" ADD CONSTRAINT "FK_1063fb7dc3313ef22f08555234d" FOREIGN KEY ("employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_98271e4a83052aeca9aa11fd3ca" FOREIGN KEY ("transaction_type_id") REFERENCES "transaction_type"("transaction_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_bd17b902fc55fc2f9800d7074b6" FOREIGN KEY ("branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_bde6f6e09fa87d81503a9b3bf99" FOREIGN KEY ("sale_id") REFERENCES "sale"("sale_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_6e5953eaeb750ec63eed380bb03" FOREIGN KEY ("employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_8796a37f4c3702cfd76ecd7610b" FOREIGN KEY ("cash_session_id") REFERENCES "cash_session"("cash_session_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_7051a93fb95c8963ce1cd6f8d95" FOREIGN KEY ("branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_89809b48d46cc3eae0565c016e4" FOREIGN KEY ("customer_id") REFERENCES "customer"("customer_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_667f785b671873c471e903e8f16" FOREIGN KEY ("employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_947f1c5ded800c49df8fc43195c" FOREIGN KEY ("cash_session_id") REFERENCES "cash_session"("cash_session_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("permission_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_135936b6918bd375a4479b92311" FOREIGN KEY ("employee_id") REFERENCES "employee"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_a23468d869e3db239e8f3219aa4" FOREIGN KEY ("branch_office_id") REFERENCES "branch_office"("branch_office_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_23de344b8c3b115a80d69cb25e3" FOREIGN KEY ("employee_role_id") REFERENCES "employee_role"("employee_role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194" FOREIGN KEY ("address_id") REFERENCES "address"("address_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_office" ADD CONSTRAINT "FK_b60100709d7f1bba4028c87bf99" FOREIGN KEY ("address_id") REFERENCES "address"("address_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_office" ADD CONSTRAINT "FK_208cecb8bf36c515636b326c6ab" FOREIGN KEY ("establishment_id") REFERENCES "establishment"("establishment_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branch_office" DROP CONSTRAINT "FK_208cecb8bf36c515636b326c6ab"`);
        await queryRunner.query(`ALTER TABLE "branch_office" DROP CONSTRAINT "FK_b60100709d7f1bba4028c87bf99"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_23de344b8c3b115a80d69cb25e3"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_a23468d869e3db239e8f3219aa4"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_135936b6918bd375a4479b92311"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_947f1c5ded800c49df8fc43195c"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_667f785b671873c471e903e8f16"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_89809b48d46cc3eae0565c016e4"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_7051a93fb95c8963ce1cd6f8d95"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_8796a37f4c3702cfd76ecd7610b"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_6e5953eaeb750ec63eed380bb03"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_bde6f6e09fa87d81503a9b3bf99"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_bd17b902fc55fc2f9800d7074b6"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_98271e4a83052aeca9aa11fd3ca"`);
        await queryRunner.query(`ALTER TABLE "cash_session" DROP CONSTRAINT "FK_1063fb7dc3313ef22f08555234d"`);
        await queryRunner.query(`ALTER TABLE "cash_session" DROP CONSTRAINT "FK_f823f4771aa4181f79c13bc6283"`);
        await queryRunner.query(`ALTER TABLE "cash_register" DROP CONSTRAINT "FK_516c78eb890a8647e13328e328f"`);
        await queryRunner.query(`ALTER TABLE "sale_payment" DROP CONSTRAINT "FK_ed5e4187840fb479d16c60935e0"`);
        await queryRunner.query(`ALTER TABLE "sale_payment" DROP CONSTRAINT "FK_e6064f0e7a5404cca890a994c35"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_8f79a9318b851af5c24cabfd510"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_6f193a6e12bed09dc343ad057ab"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_aa365031a50f63a92601192e5f5"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_2eb5ce4324613b4b457c364f4a2"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_9442f51326c1f2588083345d8fb"`);
        await queryRunner.query(`ALTER TABLE "season" DROP CONSTRAINT "FK_6fe6e856caf37532769499a2baf"`);
        await queryRunner.query(`ALTER TABLE "lot" DROP CONSTRAINT "FK_89eb6f642cad1024527b0f13e54"`);
        await queryRunner.query(`ALTER TABLE "lot" DROP CONSTRAINT "FK_e79764f0f61ae488d54f3170923"`);
        await queryRunner.query(`ALTER TABLE "suplier" DROP CONSTRAINT "FK_99627221092cc52719692a21ff6"`);
        await queryRunner.query(`ALTER TABLE "suplier" DROP CONSTRAINT "FK_60bc300997b579e59bc75ad3601"`);
        await queryRunner.query(`ALTER TABLE "lot_unit_purchase" DROP CONSTRAINT "FK_7e93cb81b9500f42b10cdf3f6dc"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_735e19a378152b4fadfb7c82852"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_732fdb1f76432d65d2c136340dc"`);
        await queryRunner.query(`ALTER TABLE "returns" DROP CONSTRAINT "FK_5f8ec9dd564e7ae386c8bfb3421"`);
        await queryRunner.query(`ALTER TABLE "returns" DROP CONSTRAINT "FK_b3994d9ce84eb746e266929eb43"`);
        await queryRunner.query(`ALTER TABLE "returns" DROP CONSTRAINT "FK_c79e321a198b9a794c9b4197290"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_612f938aeee343d52fb045e3b60"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_1ae9614b29392c195f75ff63265"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_967eed20693cb0a99a63501d329"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_bd077bffe7cc45942115d1e1a6f"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_a328ca7219e70e3222adaaf43e3"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_d4aa6f098fca4e9f3e5cc20efaa"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_e2bad4f0b033667a33ea21159d9"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_a2129b235bd560a0a725ae3404b"`);
        await queryRunner.query(`ALTER TABLE "brand" DROP CONSTRAINT "FK_0574a2ace361e0a309629993228"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_2e1a2e8a187a8ee29bfe143034a"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_c48f6f5c750b8e0de0c4b41bde7"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_23810fb397050d8ac37dae44ff6"`);
        await queryRunner.query(`DROP TABLE "establishment"`);
        await queryRunner.query(`DROP TABLE "branch_office"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP TYPE "public"."employee_gender_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TABLE "sale"`);
        await queryRunner.query(`DROP TYPE "public"."sale_status_enum"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TABLE "transaction_type"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_account_type_enum"`);
        await queryRunner.query(`DROP TABLE "cash_session"`);
        await queryRunner.query(`DROP TABLE "cash_register"`);
        await queryRunner.query(`DROP TABLE "sale_payment"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TABLE "sale_detail"`);
        await queryRunner.query(`DROP TYPE "public"."sale_detail_salefor_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57aaf9f1e2f450783692c0d977"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7fc615c93ad77e766374b5e1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8257684c84ab2a533ec9f76be3"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TYPE "public"."product_unit_of_measure_enum"`);
        await queryRunner.query(`DROP TABLE "season"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47dc7829fdca47653512ca28e2"`);
        await queryRunner.query(`DROP TABLE "lot"`);
        await queryRunner.query(`DROP TYPE "public"."lot_purchase_unit_enum"`);
        await queryRunner.query(`DROP TABLE "suplier"`);
        await queryRunner.query(`DROP TABLE "lot_unit_purchase"`);
        await queryRunner.query(`DROP TYPE "public"."lot_unit_purchase_unit_enum"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "returns"`);
        await queryRunner.query(`DROP TABLE "transfer"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_to_location_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_from_location_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_item_location_enum"`);
        await queryRunner.query(`DROP TABLE "brand"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP TABLE "employee_role"`);
    }

}
